version: '3.8'

services:
  app:
    image: zapvitrine:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://zap_user:zap_password@db:5432/zap_db?schema=public
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=production
    networks:
      - zap_network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: zap_user
      POSTGRES_PASSWORD: zap_password
      POSTGRES_DB: zap_db
    networks:
      - zap_network
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  zap_network:
    driver: overlay

volumes:
  db_data:
